# Exploratory Data Analysis

### Dependencies

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from itertools import product

from sklearn.model_selection import train_test_split
from sklearn.model_selection import PredefinedSplit
pd.set_option('display.max_columns', 500)

### Reading Data

In [2]:
df = pd.read_csv("../data/df_clean.csv")
df["trans_date"] = pd.to_datetime(df["trans_date"]) 
float_columns = ["original_gross_amt", "billing_gross_amt", "trans_tax_amt"]
for col in float_columns:
    df = df[df[col] >= 0]
df["merchant_name_cluster"] = df["merchant_name_cluster"].astype(str)

### Description of data

En cada dia, una persona (o tarjeta) puede hacer varias compras de diferentes direcciones a diferentes empresas, por ejemplo:

In [3]:
df.groupby(["card_number", "trans_date", "directorate"]).size().sort_values(ascending=False).head()

card_number  trans_date  directorate
6607         2023-08-31  digital_and_customer_services    85
             2023-08-30  digital_and_customer_services    80
6667         2023-05-09  city_operations                  61
             2022-03-08  neighbourhoods                   60
             2023-01-23  neighbourhoods                   52
dtype: int64

### Creación de tabla universo

Nos interesa tener una tabla con un solo registro por cada tarjeta y cada fin de mes. El fin de esta tabla sería el de predecir futuros el comportamiento el gasto el siguiente fin de mes por tarjeta.

Para cada fin de mes del siguiente periodo de tiempo

In [4]:
start, end = df["trans_date"].min(), df["trans_date"].max()
start, end

(Timestamp('2022-02-01 00:00:00'), Timestamp('2024-05-03 00:00:00'))

generamos una tabla con un registro por número de cuenta.

In [5]:
dates = pd.date_range(start=start, end=end, freq='ME')
card_numbers = df["card_number"].unique().tolist()

In [6]:
# Crear todas las combinaciones posibles
combinations = list(product(dates, card_numbers))

# Convertir las combinaciones en un dataframe
df_universe = pd.DataFrame(combinations, columns=['date', 'card_number'])
df_universe.sort_values(["card_number", "date"], inplace=True)

In [7]:
df_universe.head()

           date  card_number
511  2022-02-28           12
1477 2022-03-31           12
2443 2022-04-30           12
3409 2022-05-31           12
4375 2022-06-30           12

### Computo de columnas

In [8]:
df["date"] = df["trans_date"].dt.to_period('M').dt.to_timestamp('M')

concept_col = "directorate"
amount_col = "original_gross_amt"

stats = {f"sum_{amount_col}" : (amount_col, "sum"),
         "count" : (amount_col, "count")}

df_summary = df.groupby(["date", "card_number", concept_col]).agg(**stats)

df_summary = df_summary.pivot_table(index=["date", "card_number"], columns=concept_col, values=[f"sum_{amount_col}", "count"], fill_value=0)
df_summary.columns = ['_'.join(col).strip() for col in df_summary.columns.values]

key_columns = ["date", "card_number"]
df_universe_2 = df_universe.merge(df_summary, on=key_columns, how="left")
df_universe_2.fillna(0, inplace=True)

In [9]:
concept_col = "merchant_name_cluster"

stats = {f"sum_{amount_col}" : (amount_col, "sum"),
         "count" : (amount_col, "count")}

df_summary = df.groupby(["date", "card_number", concept_col]).agg(**stats)

df_summary = df_summary.pivot_table(index=["date", "card_number"], columns=concept_col, values=[f"sum_{amount_col}", "count"], fill_value=0)
df_summary.columns = ['_'.join(col).strip() for col in df_summary.columns.values]

df_universe_3 = df_universe_2.merge(df_summary, on=key_columns, how="left")
df_universe_3.fillna(0, inplace=True)

df_universe_3.head()

,date,card_number,count_acivico,count_adult_social_care,count_birmingham_childrens_trust,count_children_and_families,count_city_housing,count_city_operations,count_commonwealth_games,count_council_management,count_cypandf,count_digital_and_customer_services,count_education_and_skills,count_finance_and_governance,count_human_resources,count_inclusive_growth,count_neighbourhoods,count_partnership_insight_and_prevention,count_place_prosperity_and_sustainability,count_schools,count_strategic_services,count_strategy_equalities_and_partnership,sum_original_gross_amt_acivico,sum_original_gross_amt_adult_social_care,sum_original_gross_amt_birmingham_childrens_trust,sum_original_gross_amt_children_and_families,sum_original_gross_amt_city_housing,sum_original_gross_amt_city_operations,sum_original_gross_amt_commonwealth_games,sum_original_gross_amt_council_management,sum_original_gross_amt_cypandf,sum_original_gross_amt_digital_and_customer_services,sum_original_gross_amt_education_and_skills,sum_original_gross_amt_finance_and_governance,sum_original_gross_amt_human_resources,sum_original_gross_amt_inclusive_growth,sum_original_gross_amt_neighbourhoods,sum_original_gross_amt_partnership_insight_and_prevention,sum_original_gross_amt_place_prosperity_and_sustainability,sum_original_gross_amt_schools,sum_original_gross_amt_strategic_services,sum_original_gross_amt_strategy_equalities_and_partnership,count_0,count_1,count_2,count_3,count_4,count_5,count_6,count_7,count_8,count_9,sum_original_gross_amt_0,sum_original_gross_amt_1,sum_original_gross_amt_2,sum_original_gross_amt_3,sum_original_gross_amt_4,sum_original_gross_amt_5,sum_original_gross_amt_6,sum_original_gross_amt_7,sum_original_gross_amt_8,sum_original_gross_amt_9
0,2022-02-28,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-03-31,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2022-04-30,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2022-05-31,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2022-06-30,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Tiempo desde la última compra

In [10]:
df_last_purchase = df_universe.merge(df[["trans_date", "card_number"]], on="card_number")
df_last_purchase = df_last_purchase.query("date >= trans_date")
df_last_purchase.drop_duplicates(inplace=True)

df_last_purchase["days_since_last_purchase"] = (df_last_purchase['date'] - df_last_purchase['trans_date']).dt.days
idx = df_last_purchase.groupby(["date", "card_number"])["days_since_last_purchase"].idxmin()
df_last_purchase = df_last_purchase.loc[idx]
df_last_purchase.drop(columns="trans_date", inplace=True)
df_last_purchase.sort_values(["card_number", "date"], inplace=True)

In [11]:
df_last_purchase.head()

          date  card_number  days_since_last_purchase
105 2022-10-31           12                         4
119 2022-11-30           12                        22
131 2022-12-31           12                        53
143 2023-01-31           12                        84
155 2023-02-28           12                       112

In [12]:
df_universe_4 = df_universe_3.merge(df_last_purchase, on=key_columns, how="inner")

In [13]:
df_universe_4.head()

,date,card_number,count_acivico,count_adult_social_care,count_birmingham_childrens_trust,count_children_and_families,count_city_housing,count_city_operations,count_commonwealth_games,count_council_management,count_cypandf,count_digital_and_customer_services,count_education_and_skills,count_finance_and_governance,count_human_resources,count_inclusive_growth,count_neighbourhoods,count_partnership_insight_and_prevention,count_place_prosperity_and_sustainability,count_schools,count_strategic_services,count_strategy_equalities_and_partnership,sum_original_gross_amt_acivico,sum_original_gross_amt_adult_social_care,sum_original_gross_amt_birmingham_childrens_trust,sum_original_gross_amt_children_and_families,sum_original_gross_amt_city_housing,sum_original_gross_amt_city_operations,sum_original_gross_amt_commonwealth_games,sum_original_gross_amt_council_management,sum_original_gross_amt_cypandf,sum_original_gross_amt_digital_and_customer_services,sum_original_gross_amt_education_and_skills,sum_original_gross_amt_finance_and_governance,sum_original_gross_amt_human_resources,sum_original_gross_amt_inclusive_growth,sum_original_gross_amt_neighbourhoods,sum_original_gross_amt_partnership_insight_and_prevention,sum_original_gross_amt_place_prosperity_and_sustainability,sum_original_gross_amt_schools,sum_original_gross_amt_strategic_services,sum_original_gross_amt_strategy_equalities_and_partnership,count_0,count_1,count_2,count_3,count_4,count_5,count_6,count_7,count_8,count_9,sum_original_gross_amt_0,sum_original_gross_amt_1,sum_original_gross_amt_2,sum_original_gross_amt_3,sum_original_gross_amt_4,sum_original_gross_amt_5,sum_original_gross_amt_6,sum_original_gross_amt_7,sum_original_gross_amt_8,sum_original_gross_amt_9,days_since_last_purchase
0,2022-10-31,12,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,322.91,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,1.0,0.0,0.0,1.0,3.0,0.0,1.5,0.0,142.35,0.0,80.68,0.0,0.0,13.0,85.38,4
1,2022-11-30,12,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58.68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,58.68,22
2,2022-12-31,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,53
3,2023-01-31,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,84
4,2023-02-28,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,112

### Columna target

In [14]:
cols = [col for col in df_summary.columns if "sum" in col]
df_target = df_universe_4[key_columns].copy()
df_target["amount_spent_1m"] = df_universe_4[cols].sum(axis=1)
df_universe_4["amount_spent"] = df_universe_4[cols].sum(axis=1)

df_target['date_1m'] = df_target['date'] - pd.offsets.MonthEnd(1)
df_target.drop(columns="date", inplace=True)

df_universe_5 = df_universe_4.merge(df_target, left_on=key_columns, right_on=['date_1m', 'card_number'], how="inner")
df_universe_5.drop(columns="date_1m", inplace=True)

In [15]:
df_universe_5.head()

,date,card_number,count_acivico,count_adult_social_care,count_birmingham_childrens_trust,count_children_and_families,count_city_housing,count_city_operations,count_commonwealth_games,count_council_management,count_cypandf,count_digital_and_customer_services,count_education_and_skills,count_finance_and_governance,count_human_resources,count_inclusive_growth,count_neighbourhoods,count_partnership_insight_and_prevention,count_place_prosperity_and_sustainability,count_schools,count_strategic_services,count_strategy_equalities_and_partnership,sum_original_gross_amt_acivico,sum_original_gross_amt_adult_social_care,sum_original_gross_amt_birmingham_childrens_trust,sum_original_gross_amt_children_and_families,sum_original_gross_amt_city_housing,sum_original_gross_amt_city_operations,sum_original_gross_amt_commonwealth_games,sum_original_gross_amt_council_management,sum_original_gross_amt_cypandf,sum_original_gross_amt_digital_and_customer_services,sum_original_gross_amt_education_and_skills,sum_original_gross_amt_finance_and_governance,sum_original_gross_amt_human_resources,sum_original_gross_amt_inclusive_growth,sum_original_gross_amt_neighbourhoods,sum_original_gross_amt_partnership_insight_and_prevention,sum_original_gross_amt_place_prosperity_and_sustainability,sum_original_gross_amt_schools,sum_original_gross_amt_strategic_services,sum_original_gross_amt_strategy_equalities_and_partnership,count_0,count_1,count_2,count_3,count_4,count_5,count_6,count_7,count_8,count_9,sum_original_gross_amt_0,sum_original_gross_amt_1,sum_original_gross_amt_2,sum_original_gross_amt_3,sum_original_gross_amt_4,sum_original_gross_amt_5,sum_original_gross_amt_6,sum_original_gross_amt_7,sum_original_gross_amt_8,sum_original_gross_amt_9,days_since_last_purchase,amount_spent,amount_spent_1m
0,2022-10-31,12,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,322.91,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,1.0,0.0,0.0,1.0,3.0,0.0,1.5,0.0,142.35,0.0,80.68,0.0,0.0,13.0,85.38,4,322.91,58.68
1,2022-11-30,12,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58.68,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,58.68,22,58.68,0.00
2,2022-12-31,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,53,0.00,0.00
3,2023-01-31,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,84,0.00,0.00
4,2023-02-28,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,0.0,0.0,0.00,112,0.00,0.00

In [16]:
df_universe_5.shape

(20083, 65)

In [17]:
df_universe_5.to_csv("../data/df_target.csv", index=False)